=== api-evangelist/amazon-iam-access-analyzer/json-schema/iam-access-analyzer-analyzer-summary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-iam-access-analyzer/refs/heads/main/json-schema/iam-access-analyzer-analyzer-summary-schema.json",
  "title": "AnalyzerSummary",
  "description": "Contains information about the analyzer.",
  "type": "object",
  "properties": {
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AnalyzerArn"
        },
        {
          "description": "The ARN of the analyzer."
        }
      ]
    },
    "name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Name"
        },
        {
          "description": "The name of the analyzer."
        }
      ]
    },
    "type": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Type"
        },
        {
          "description": "The type of analyzer, which corresponds to the zone of trust chosen for the analyzer."
        }
      ]
    },
    "createdAt": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": "A timestamp for the time at which the analyzer was created."
        }
      ]
    },
    "lastResourceAnalyzed": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String"
        },
        {
          "description": "The resource that was most recently analyzed by the analyzer."
        }
      ]
    },
    "lastResourceAnalyzedAt": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": "The time at which the most recently analyzed resource was analyzed."
        }
      ]
    },
    "tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagsMap"
        },
        {
          "description": "The tags added to the analyzer."
        }
      ]
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AnalyzerStatus"
        },
        {
          "description": "The status of the analyzer. An <code>Active</code> analyzer successfully monitors supported resources and generates new findings. The analyzer is <code>Disabled</code> when a user action, such as removing trusted access for Identity and Access Management Access Analyzer from Organizations, causes the analyzer to stop generating new findings. The status is <code>Creating</code> when the analyzer creation is in progress and <code>Failed</code> when the analyzer creation has failed. "
        }
      ]
    },
    "statusReason": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StatusReason"
        },
        {
          "description": "The <code>statusReason</code> provides more details about the current status of the analyzer. For example, if the creation for the analyzer fails, a <code>Failed</code> status is returned. For an analyzer with organization as the type, this failure can be due to an issue with creating the service-linked roles required in the member accounts of the Amazon Web Services organization."
        }
      ]
    }
  },
  "required": [
    "arn",
    "name",
    "type",
    "createdAt",
    "status"
  ]
}

=== api-evangelist/amazon-iam-access-analyzer/examples/iam-access-analyzer-analyzer-summary-example.json
{
  "arn": "arn:aws:iam::123456789012:role/ExampleRole",
  "name": "example-resource-name",
  "type": "CUSTOM",
  "createdAt": "example-value",
  "lastResourceAnalyzed": "example-value",
  "lastResourceAnalyzedAt": "example-value",
  "tags": "example-value",
  "status": "ACTIVE",
  "statusReason": "ACTIVE"
}
